org: dohyeon5626
app: baekjoon-problem-letter
service: baekjoon-problem-letter

provider:
  name: aws
  runtime: nodejs22.x

  iam:
    role:
      statements:

        - Effect: "Allow"
          Action:
            - "dynamodb:PutItem"
            - "dynamodb:DeleteItem"
            - "dynamodb:Scan"
            - "dynamodb:UpdateItem"
            - "dynamodb:Query"
          Resource:
            - "arn:aws:dynamodb:${aws:region}:${aws:accountId}:table/${env:TABLE}"
            - "arn:aws:dynamodb:${aws:region}:${aws:accountId}:table/${env:TABLE}/index/NextGeneratedDateIndex"

        - Effect: "Allow"
          Action:
            - "ses:SendEmail"
            - "ses:SendRawEmail"
          Resource:
            - "arn:aws:ses:${aws:region}:${aws:accountId}:identity/${env:SENDER_EMAIL}"

        - Effect: "Allow"
          Action:
            - "scheduler:CreateSchedule"
            - "scheduler:GetSchedule"
            - "scheduler:DeleteSchedule"
          Resource: "*"

        - Effect: "Allow"
          Action:
            - "iam:PassRole"
          Resource:
            - !Sub "arn:aws:iam::${AWS::AccountId}:role/ProblemUpdateSchedulerRole"

functions:

  api:
    handler: app.application
    events:
      - httpApi: "*"

  letterEvent:
    handler: letter-event.run
    events:
      - schedule: cron(0,30 21-23 * * ? *) # KST 06:00 ~ 08:30 (UTC 전날 21:00 ~ 23:30)
      - schedule: cron(0,30 0-14 * * ? *) # KST 09:00 ~ 23:30 (UTC 00:00 ~ 14:30)
    timeout: 300
    memorySize: 1024

  tierUpdateEvent:
    handler: tier-update-event.run
    events:
      - schedule: cron(0 15 * * ? *)
    timeout: 300
    memorySize: 1024
    environment:
      SCHEDULER_ROLE_ARN: !GetAtt SchedulerExecutionRole.Arn
      TARGET_LAMBDA_ARN: "arn:aws:lambda:${aws:region}:${aws:accountId}:function:${self:service}-${sls:stage}-tierUpdateEvent"

resources:
  Resources:
    SchedulerExecutionRole:
      Type: AWS::IAM::Role
      Properties:
        RoleName: ProblemUpdateSchedulerRole
        AssumeRolePolicyDocument:
          Version: '2012-10-17'
          Statement:
            - Effect: Allow
              Principal:
                Service: scheduler.amazonaws.com
              Action: sts:AssumeRole
        Policies:
          - PolicyName: InvokeLambdaPolicy
            PolicyDocument:
              Version: '2012-10-17'
              Statement:
                - Effect: Allow
                  Action: lambda:InvokeFunction
                  Resource: "arn:aws:lambda:${aws:region}:${aws:accountId}:function:${self:service}-${sls:stage}-tierUpdateEvent"

plugins:
  - serverless-offline
  - serverless-dotenv-plugin

package:
  exclude:
    - .env