org: dohyeon5626
app: baekjoon-problem-letter
service: baekjoon-problem-letter

provider:
  name: aws
  runtime: nodejs22.x

  iam:
    role:
      statements:
        - Effect: "Allow"
          Action:
            - "dynamodb:PutItem"
            - "dynamodb:DeleteItem"
          Resource:
            - "arn:aws:dynamodb:${aws:region}:${aws:accountId}:table/${env:TABLE}"
        - Effect: "Allow"
          Action:
            - "ses:SendEmail"
            - "ses:SendRawEmail"
          Resource:
            - "arn:aws:ses:${aws:region}:${aws:accountId}:identity/${env:SENDER_EMAIL}"

functions:
  api:
    handler: app.application
    events:
      - httpApi: "*"
  letterEvent:
    handler: letter-event.run
    timeout: 300
    memorySize: 1024

plugins:
  - serverless-offline
  - serverless-dotenv-plugin

package:
  exclude:
    - .env