org: dohyeon5626
app: baekjoon-problem-letter
service: baekjoon-problem-letter

provider:
  name: aws
  runtime: nodejs22.x

  iam:
    role:
      statements:
        - Effect: "Allow"
          Action:
            - "dynamodb:PutItem"
            - "dynamodb:DeleteItem"
            - "dynamodb:Scan"
            - "dynamodb:UpdateItem"
          Resource:
            - "arn:aws:dynamodb:${aws:region}:${aws:accountId}:table/${env:TABLE}"
        - Effect: "Allow"
          Action:
            - "ses:SendEmail"
            - "ses:SendRawEmail"
          Resource:
            - "arn:aws:ses:${aws:region}:${aws:accountId}:identity/${env:SENDER_EMAIL}"

functions:
  api:
    handler: app.application
    events:
      - httpApi: "*"
  letterEvent:
    handler: letter-event.run
    events:
      - schedule: cron(0,30 21-23 * * ? *) # KST 06:00 ~ 08:30 (UTC 전날 21:00 ~ 23:30)
      - schedule: cron(0,30 0-14 * * ? *) # KST 09:00 ~ 23:30 (UTC 00:00 ~ 14:30)
    timeout: 300
    memorySize: 1024
  tierUpdateEvent:
    handler: tier-update-event.run
    events:
      - schedule: cron(0 15 * * ? *)
    timeout: 300
    memorySize: 1024

plugins:
  - serverless-offline
  - serverless-dotenv-plugin

package:
  exclude:
    - .env