org: dohyeon5626
app: monitoring-system
service: monitoring-system

provider:
  name: aws
  runtime: nodejs22.x

functions:
  alimHandler:
    handler: handler.run
    events:
      - schedule: cron(10 0 * * ? *)
    timeout: 30
    memorySize: 1024

plugins:
  - serverless-dotenv-plugin

package:
  exclude:
    - .env