org: dohyeon5626
app: time-capsule
service: time-capsule

provider:
  name: aws
  runtime: nodejs20.x

  iam:
    role:
      statements:

        - Effect: "Allow"
          Action:
            - "dynamodb:PutItem"
            - "dynamodb:GetItem"
            - "dynamodb:UpdateItem"
            - "dynamodb:Query"
            - "dynamodb:DescribeStream"
            - "dynamodb:GetRecords"
            - "dynamodb:GetShardIterator"
            - "dynamodb:ListStreams"
          Resource:
            - "arn:aws:dynamodb:${aws:region}:${aws:accountId}:table/${env:TABLE}"
            - "arn:aws:dynamodb:${aws:region}:${aws:accountId}:table/${env:TABLE}/index/OpenStatusIndex"
            - "arn:aws:dynamodb:${aws:region}:${aws:accountId}:table/${env:TABLE}/index/OpenDateIndex"
            - "${env:STREAM_ARN}"

        - Effect: "Allow"
          Action:
            - "s3:PutObject"
            - "s3:DeleteObject"
          Resource: 
          - "arn:aws:s3:::${env:BUCKET}/*"

        - Effect: "Allow"
          Action:
            - "ses:SendEmail"
            - "ses:SendRawEmail"
          Resource:
            - "arn:aws:ses:${aws:region}:${aws:accountId}:identity/${env:SENDER_EMAIL}"

        - Effect: "Allow"
          Action:
            - "scheduler:CreateSchedule"
            - "scheduler:GetSchedule"
            - "scheduler:DeleteSchedule"
          Resource: "*"
        
        - Effect: "Allow"
          Action:
            - "iam:PassRole"
          Resource:
            - !Sub "arn:aws:iam::${AWS::AccountId}:role/TimeCapsuleSchedulerRole"

functions:

  api:
    handler: app.application
    events:
      - httpApi: "*"

  dbEvent:
    handler: db-event.run
    events:
      - stream:
          type: dynamodb
          arn: "${env:STREAM_ARN}"
          batchSize: 100
          startingPosition: LATEST
    environment:
      SCHEDULER_ROLE_ARN: !GetAtt SchedulerExecutionRole.Arn
      TARGET_LAMBDA_ARN: !GetAtt AlimEventLambdaFunction.Arn

  alimEvent:
    handler: alim-event.run

resources:
  Resources:
    SchedulerExecutionRole:
      Type: AWS::IAM::Role
      Properties:
        RoleName: TimeCapsuleSchedulerRole
        AssumeRolePolicyDocument:
          Version: '2012-10-17'
          Statement:
            - Effect: Allow
              Principal:
                Service: scheduler.amazonaws.com
              Action: sts:AssumeRole
        Policies:
          - PolicyName: InvokeLambdaPolicy
            PolicyDocument:
              Version: '2012-10-17'
              Statement:
                - Effect: Allow
                  Action: lambda:InvokeFunction
                  Resource: !GetAtt AlimEventLambdaFunction.Arn

plugins:
  - serverless-offline
  - serverless-dotenv-plugin

package:
  exclude:
    - .env